extends: airbnb

plugins:
  - react
  - jsx-a11y
  - import

env:
  browser: true
  es6: true
  node: true

rules: 
  new-cap:
    - error
    - capIsNewExceptionPattern: "^express."
  react/no-unused-prop-types:
    - error
    - skipShapeProps: true

